import { _electron as electron, expect } from '@playwright/test';
import electronPath from 'electron';
import path from 'node:path';
import fs from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
const results = path.resolve('test-results');
await fs.mkdir(results, {recursive:true});
const profile = path.join(results, `profile-${randomUUID()}`);
const packaged=process.env.ASTER_PACKAGED_EXE;
const instance = await electron.launch({executablePath:packaged ?? electronPath,args:packaged ? [] : ['.'],cwd:process.cwd(),env:{...process.env,ASTER_USER_DATA:profile},timeout:30000});
const errors=[];
try {
  const page = await instance.firstWindow();
  page.on('pageerror', error=>errors.push(error.message));
  await expect(page.getByRole('heading',{name:'A wider perspective.'})).toBeVisible();
  await expect(page.locator('.tree-note')).toHaveCount(17);
  await page.screenshot({path:path.join(results,'aster-graph.png')});
  await page.getByTitle('New note (Ctrl+N)',{exact:true}).click();
  await page.getByLabel('File path within this vault',{exact:true}).fill('02 Retrieval/Smoke note.md');
  await page.getByRole('button',{name:'Create',exact:true}).click();
  await expect(page.locator('.note-heading h2')).toHaveText('Smoke note');
  const content='# Smoke note\n\nA durable note about semantic retrieval and embeddings.\n\n[[Hybrid search]]\n\n#retrieval #search';
  await page.locator('.cm-content').fill(content);
  await expect(page.locator('.editor-footer')).toContainText('All changes saved',{timeout:10000});
  const snapshot=await page.evaluate(()=>window.aster.load());
  const created=snapshot.notes.find(n=>n.title==='Smoke note');
  expect(created.content).toBe(content);
  expect(await fs.readFile(path.join(snapshot.root,created.path),'utf8')).toBe(content);
  await page.getByRole('button',{name:'Connections',exact:true}).click();
  await expect(page.locator('.connection-item')).toContainText('Hybrid search');
  await page.getByLabel('Relationship',{exact:true}).selectOption('supports');
  await page.getByLabel('Connect to',{exact:true}).selectOption(snapshot.notes.find(n=>n.title==='Graph retrieval').id);
  await page.getByRole('button',{name:'Add connection',exact:true}).click();
  await expect(page.locator('.connection-item').filter({hasText:'Graph retrieval'})).toContainText('supports');
  await page.getByRole('button',{name:'Read formatted note',exact:true}).click();
  await expect(page.locator('.markdown-preview')).toContainText('A durable note');
  await page.getByRole('button',{name:'Graph',exact:true}).click();
  await expect(page.locator('.dock-pane')).toHaveCount(1);
  await page.locator('.tree-note').filter({hasText:'Smoke note'}).click();
  await expect(page.locator('.note-heading h2')).toHaveText('Smoke note');
  await page.getByRole('button',{name:'Graph',exact:true}).click();
  await expect(page.locator('.dock-pane')).toHaveCount(1);
  // A pre-fix saved graph tab may contain a noteId; it must never count as an editor.
  await page.evaluate(async id=>{const m=await window.aster.loadModules();m.state.workspace.layout.tabs[0].noteId=id;await window.aster.saveModules({vaultId:m.vaultId,revision:m.revision,state:m.state});},created.id);
  await page.keyboard.press('Control+s');
  await expect.poll(()=>page.evaluate(()=>!window.dispatchEvent(new Event('beforeunload',{cancelable:true})))).toBe(false);
  await page.reload();await expect(page.locator('.tree-note')).toHaveCount(18);
  await page.locator('.tree-note').filter({hasText:'Smoke note'}).click();
  await expect(page.locator('.note-heading h2')).toHaveText('Smoke note');
  await page.getByRole('button',{name:'Graph',exact:true}).click();
  await expect(page.locator('.dock-pane')).toHaveCount(1);
  await page.getByRole('button',{name:'Appearance',exact:true}).click();
  await page.getByRole('button',{name:'Save view',exact:true}).click();
  await page.getByLabel('View name',{exact:true}).fill('Retrieval map');
  await page.getByRole('button',{name:'Create',exact:true}).click();
  await expect(page.getByLabel('SAVED VIEW',{exact:true})).toHaveValue(/.+/);
  await page.getByRole('button',{name:'Orbit',exact:true}).click();
  await page.getByLabel('Filter graph',{exact:true}).fill('tag:retrieval');
  await expect(page.locator('.graph-top p')).not.toContainText('18 notes');
  await page.getByTitle('Clear graph filter',{exact:true}).click();
  await page.getByRole('button',{name:'Organic',exact:true}).click();
  await expect(page.getByRole('button',{name:'Organic',exact:true})).toBeEnabled({timeout:15000});
  await page.getByRole('button',{name:'Clusters',exact:true}).click();
  await page.getByTitle('Reload from disk',{exact:true}).click();
  const arranged=await page.evaluate(()=>window.aster.load());
  const arrangedView=arranged.settings.views.find(v=>v.id===arranged.settings.activeView);
  const position=arrangedView.positions[created.id];
  const canvas=page.locator('canvas'); const bounds=await canvas.boundingBox();
  const points=arranged.notes.map(n=>arrangedView.positions[n.id]);
  const minX=Math.min(...points.map(p=>p.x)),maxX=Math.max(...points.map(p=>p.x)),minY=Math.min(...points.map(p=>p.y)),maxY=Math.max(...points.map(p=>p.y));
  const zoom=Math.max(.12,Math.min(1.3,(bounds.width-200)/Math.max(100,maxX-minX),(bounds.height-180)/Math.max(100,maxY-minY)));
  const nodeX=bounds.x+bounds.width/2+(position.x-(minX+maxX)/2)*zoom;
  const nodeY=bounds.y+bounds.height/2+(position.y-(minY+maxY)/2)*zoom;
  await page.mouse.move(nodeX,nodeY);await page.mouse.down();await page.mouse.move(nodeX+75,nodeY-35,{steps:8});await page.mouse.up();
  await page.getByTitle('Reload from disk',{exact:true}).click();
  const dragged=await page.evaluate(()=>window.aster.load());
  expect(dragged.settings.views.find(v=>v.id===dragged.settings.activeView).positions[created.id].x).not.toBe(position.x);
  await page.getByTitle('Keyboard shortcuts',{exact:true}).click();
  await expect(page.getByRole('heading',{name:'Make yourself at home'})).toBeVisible();
  await page.getByTitle('Close dialog',{exact:true}).click();
  await page.getByTitle('AI settings',{exact:true}).click();
  await expect(page.getByLabel('API key',{exact:true})).toHaveAttribute('type','password');
  await page.getByTitle('Close dialog',{exact:true}).click();
  await page.getByTitle('Reload from disk',{exact:true}).click();
  await expect(page.locator('.error-banner')).toHaveCount(0);
  const persisted=await page.evaluate(()=>window.aster.load());
  expect(persisted.settings.views).toHaveLength(2);
  expect(persisted.settings.relations.some(e=>e.source===created.id&&e.kind==='supports')).toBe(true);
  expect(errors).toEqual([]);
  // Native host isolation, no ambient Node in the renderer.
  expect(await page.evaluate(()=>({node:typeof window.require,process:typeof window.process}))).toEqual({node:'undefined',process:'undefined'});
  const native=await instance.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences());
  expect(native.contextIsolation).toBe(true); expect(native.sandbox).toBe(true); expect(native.nodeIntegration).toBe(false);
  await page.getByRole('button',{name:'Discover',exact:true}).click();
  await page.screenshot({path:path.join(results,'aster-discover.png')});
  await page.getByRole('button',{name:'Split',exact:true}).click();
  await page.screenshot({path:path.join(results,'aster-split.png')});
  // Concurrent external edit must preserve both disk contents and a recoverable draft.
  await fs.writeFile(path.join(snapshot.root,created.path),'External change that must survive.');
  await page.locator('.cm-content').fill('# My unsaved local draft');
  await expect(page.locator('.error-banner')).toContainText('Save conflict',{timeout:10000});
  await page.getByRole('button',{name:'Save draft copy',exact:true}).click();
  await expect(page.locator('.error-banner')).toHaveCount(0);
  expect(await fs.readFile(path.join(snapshot.root,created.path),'utf8')).toBe('External change that must survive.');
  const recovered=await page.evaluate(()=>window.aster.load());
  expect(recovered.notes.some(n=>n.path.includes('(draft ')&&n.content==='# My unsaved local draft')).toBe(true);
  console.log(JSON.stringify({ok:true,packaged:!!packaged,checks:['desktop launch','nested note creation','autosave to Markdown','wikilinks','typed relationships','formatted preview','saved views','filtering','worker layout','drag position persistence','AI settings privacy','reopen persistence','sandbox isolation','external edit conflict recovery'],screenshots:results,profile}));
} catch(error) { console.error(error); const pages=instance.windows(); if(pages[0]) await pages[0].screenshot({path:path.join(results,'failure.png')}).catch(()=>{}); throw error; }
finally { await instance.close(); }
